name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies (SmartAPI.Application)
      run: dotnet restore SmartAPI.Application.csproj

    - name: Build (SmartAPI.Application)
      run: dotnet build SmartAPI.Application.csproj
