name: Build SmartAPI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore project (SmartAPI.Application)
      run: dotnet restore SmartAPI/SmartAPI.Application.csproj

    - name: Build project (SmartAPI.Application)
      run: dotnet build SmartAPI/SmartAPI.Application.csproj
