# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Test Application .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    # Build the Application project
    - name: Build Application
      run: dotnet build --no-restore
      working-directory: ./SmartAPI

    # Test the Application project
    - name: Test Application
      run: dotnet test --no-build --verbosity normal
      working-directory: ./SmartAPI

    # Build the Business project
    - name: Build Business
      run: dotnet build --no-restore
      working-directory: ./SmartAPI.Business

    # Test the Business project
    - name: Test Business
      run: dotnet test --no-build --verbosity normal
      working-directory: ./SmartAPI.Business

    # Build the Infrastructure project
    - name: Build Infrastructure
      run: dotnet build --no-restore
      working-directory: ./SmartAPI.Infrastructure

    # Test the Infrastructure project
    - name: Test Infrastructure
      run: dotnet test --no-build --verbosity normal
      working-directory: ./SmartAPI.Infrastructure

    # Build the Test project
    - name: Build Test
      run: dotnet build --no-restore
      working-directory: ./SmartAPI.Test

    # Test the Test project
    - name: Test Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./SmartAPI.Test
