name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Change working directory
      run: cd SmartAPI

    - name: Build solution
      run: dotnet build --no-restore

    - name: Test solution
      run: dotnet test --no-build --verbosity normal
